// Styles
const styles = {
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(to bottom, #f3e8ff, #e9d5ff)',
  },
  appWrapper: {
    maxWidth: '448px',
    margin: '0 auto',
    backgroundColor: '#581c87',
    minHeight: '100vh',
    position: 'relative',
  },
  header: {
    backgroundColor: '#6b21a8',
    padding: '16px 24px',
  },
  headerTitle: {
    color: 'white',
    fontSize: '20px',
    fontWeight: 'bold',
    margin: 0,
  },
  content: {
    padding: '24px 16px',
    paddingBottom: '120px',
  },
  profileCard: {
    background: 'linear-gradient(to bottom right, #9333ea, #6b21a8)',
    borderRadius: '16px',
    padding: '24px',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    marginBottom: '24px',
  },
  profileHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    marginBottom: '16px',
  },
  avatar: {
    width: '80px',
    height: '80px',
    backgroundColor: '#d8b4fe',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: 'white',
    margin: '0 0 4px 0',
  },
  profileDetail: {
    color: '#e9d5ff',
    margin: '2px 0',
    fontSize: '14px',
  },
  checkInCard: {
    backgroundColor: 'rgba(107, 33, 168, 0.5)',
    borderRadius: '8px',
    padding: '12px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  checkInLabel: {
    color: 'white',
    fontWeight: '600',
    margin: 0,
  },
  checkInValue: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: 'white',
    margin: 0,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
    marginBottom: '24px',
  },
  statsCard: {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '16px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
  },
  statsCardInner: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  statsIcon: {
    padding: '12px',
    borderRadius: '8px',
  },
  statsLabel: {
    color: '#6b7280',
    fontSize: '14px',
    margin: '0 0 4px 0',
  },
  statsValue: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#1f2937',
    margin: 0,
  },
  sectionTitle: {
    color: 'white',
    fontSize: '18px',
    fontWeight: 'bold',
    marginBottom: '12px',
  },
  workoutCard: {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '16px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    marginBottom: '12px',
    transition: 'box-shadow 0.3s ease',
    cursor: 'pointer',
  },
  workoutCardHover: {
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
  },
  workoutHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '12px',
  },
  workoutTitle: {
    fontWeight: 'bold',
    color: '#1f2937',
    fontSize: '18px',
    margin: '0 0 4px 0',
  },
  workoutDate: {
    color: '#6b7280',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    margin: 0,
  },
  workoutBadge: {
    backgroundColor: '#f3e8ff',
    color: '#6b21a8',
    padding: '4px 12px',
    borderRadius: '9999px',
    fontSize: '14px',
    fontWeight: '600',
  },
  workoutStatsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '8px',
  },
  workoutStat: {
    backgroundColor: '#f9fafb',
    borderRadius: '8px',
    padding: '8px',
    textAlign: 'center',
  },
  workoutStatLabel: {
    fontSize: '12px',
    color: '#6b7280',
    margin: '0 0 2px 0',
  },
  workoutStatValue: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#1f2937',
    margin: 0,
  },
  logoContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '24px 0',
  },
  logo: {
    width: '80px',
    height: '80px',
    backgroundColor: '#7c3aed',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '8px',
  },
  logoText: {
    color: 'white',
    fontSize: '36px',
    fontWeight: 'bold',
  },
  logoSubtext: {
    color: '#6b21a8',
    fontSize: '24px',
    fontWeight: 'bold',
    margin: 0,
  },
  passwordButton: {
    width: '100%',
    backgroundColor: '#e9d5ff',
    color: '#6b21a8',
    fontWeight: '600',
    padding: '16px',
    borderRadius: '12px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '16px',
    transition: 'background-color 0.3s ease',
  },
  passwordButtonHover: {
    backgroundColor: '#d8b4fe',
  },
  bottomNav: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    maxWidth: '448px',
    margin: '0 auto',
    backgroundColor: '#6b21a8',
    borderRadius: '24px 24px 0 0',
    padding: '16px 24px',
    display: 'flex',
    justifyContent: 'space-around',
  },
  navButton: {
    padding: '12px',
    borderRadius: '50%',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
  },
  navButtonActive: {
    backgroundColor: '#7c3aed',
  },
  navButtonInactive: {
    backgroundColor: '#581c87',
  },
  loader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 0',
  },
};

export default styles;